### ISSUE TITLE
USER STORY: First Time Visitor Goal 1

### ISSUE THREAD

**Issue by jsith90** [jsith90/ebre-animal-prints#2]
As a **First Time Visitor* I can **understand the main purpose of the site** so that **I can learn more about the organisation**

### Acceptance Criteria 1:
- Acceptance Criteria 1: include about section on main page clearly detailing the operations of Ebre Animal Prints
* Acceptance Criteria 2: include details in about section on lino printing and the Ebre 
+ Acceptance Criteria 3: include pictures of the Ebre, print workshop, prints and merchandise. 

### Tasks
- [ ] Task 1: create home page with about section
- [ ] Task 2: add images
- [ ] Task 3: add header and footer with titles and links
