### ISSUE TITLE
USER STORY: First Time Visitor Goal 2

### ISSUE THREAD

**Issue by jsith90** [jsith90/ebre-animal-prints#3]
As a **first time visitor** I can **easily navigate through the site** so that **I can find content**

### Acceptance Criteria 1:
- Acceptance Criteria 1: create a simple layout and pages with about on home, gallery and contact pages
* Acceptance Criteria 2: Gallery should simply showcase the printshop, prints and merchandise.
+ Acceptance Criteria 3: Contact page with form for commissions and cafe/gallery opening times. 

### Tasks
- [ ] Task 1: Create gallery on gallery page
- [ ] Task 2: Create form on contact page
- [ ] Task 3: Add opening times and address
